### ISSUE TITLE
#query vs #raw_query

### ISSUE THREAD

**Issue by dennisvandehoef** [Garllon/graphql_connector#23]
I ran into an unexpected problem.
As far as I understood the documentation `GraphqlConnector::Backend.raw_query('query{accounts{techName}}')` and `GraphqlConnector::Backend.query('accounts', {}, ['techName'])` should be the same.

Sadly this is not:
```ruby
GraphqlConnector::Backend.raw_query('query{accounts{techName}}')
=> {"data"=>{"accounts"=>[{"techName"=>"gamer_xiotin"}]}}

GraphqlConnector::Backend.query('accounts', {}, ['techName'])
CustomAttributeError: [{"message"=>"Parse error on \")\" (RPAREN) at [1, 18]", "locations"=>[{"line"=>1, "column"=>18}]}]
from /usr/local/bundle/gems/graphql_connector-1.1.0/lib/graphql_connector/http_client.rb:37:in `verify_response!'
```

**Comment by sushie1984** [comment]
thx @dennisvandehoef  for reporting this. So far the issue can be tracked down to the following:

```ruby
GraphqlConnector::Backend.query('accounts', {}, ['techName'])
# Produces a query that looks like this:
=> "query { accounts() { techName } }"
```

I assume that the graphql server your client querying with raises an error because of the `()`. 

I suggest that we fix this by not setting an `()` when the condition params is empty/unset. What do you think about that?

**Comment by dennisvandehoef** [comment]
I testest it with the Altair plugin for chrome.
And if I use `query { accounts() { techName } }`

As expected I get an error
```
{
  "errors": [
    {
      "message": "Parse error on \")\" (RPAREN) at [1, 16]",
      "locations": [
        {
          "line": 1,
          "column": 16
        }
      ]
    }
  ]
}
```

But since my backend is built on the graphql-ruby gem I am wondering why you and @Garllon do not have the same problem? or in the examples? This could also point to a misconfiguration from my side that simply should be explained in the documentation?

**Comment by sushie1984** [comment]
> But since my backend is built on the graphql-ruby gem I am wondering why you and @Garllon do not have the same problem? 

We are actually testing it agains [`graphql (1.9.12)`](https://github.com/sushie1984/rails-graphql-server/blob/master/Gemfile.lock#L77). What is the gem version your server has? 

Also I remember that I ran into this issue once when testing aroundhomes `kp_connector` against a python graphql server :laughing:  so it is definitely a thing to fix.

**Comment by dennisvandehoef** [comment]
I made a mistake and copied the github repo name. I am using `graphql (1.10.8)`.

**Comment by sushie1984** [comment]
@dennisvandehoef 

According to [here](https://github.com/rmosolgo/graphql-ruby/pull/2344) the error response was introduced in [`1.10.0`](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020) and therefore a `()` is considered in general as an illegal form.
