### ISSUE TITLE
Deep creation of openstructs

### ISSUE THREAD

**Issue by Garllon** [Garllon/graphql_connector#9]
Currently the gem only supports OpenStruct for the first level of objects. 
The goal is to have OpenStruct for all associations it doesn't matter on which level.

This is normally a breaking change, because currently it is not like that. So i would do this for version 2.0

**Comment by sushie1984** [comment]
@Garllon What do you think about using https://github.com/aetherknight/recursive-open-struct

**Comment by Garllon** [comment]
Thanks to @A1bi  for implementing this.
